### ISSUE TITLE
Logs flooded with errors

### ISSUE THREAD

**Issue by rhuanbarreto** [openblocks-dev/openblocks#315] opened 2023-03-15 09:56 UTC
Whenever I run the container for openblocks, I have a flood of error messages:

```
openblocks-backend-1       | 2023-03-15 09:54:25.664 ERROR org.pf4j.AbstractPluginManager#loadPlugins:242    [main]: Field 'id' cannot be empty 
openblocks-backend-1       | org.pf4j.PluginRuntimeException: Field 'id' cannot be empty
openblocks-backend-1       |    at org.pf4j.AbstractPluginManager.validatePluginDescriptor(AbstractPluginManager.java:918)
openblocks-backend-1       |    at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:840)
openblocks-backend-1       |    at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:139)
openblocks-backend-1       |    at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:240)
openblocks-backend-1       |    at org.pf4j.spring.SpringPluginManager.init(SpringPluginManager.java:61)
openblocks-backend-1       |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
openblocks-backend-1       |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
openblocks-backend-1       |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
openblocks-backend-1       |    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
openblocks-backend-1       |    at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
openblocks-backend-1       |    at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
openblocks-backend-1       |    at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
openblocks-backend-1       |    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
openblocks-backend-1       |    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
openblocks-backend-1       |    at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64)
openblocks-backend-1       |    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
openblocks-backend-1       |    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420)
openblocks-backend-1       |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
openblocks-backend-1       |    at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
openblocks-backend-1       |    at com.openblocks.api.ServerApplication.main(ServerApplication.java:51)
openblocks-backend-1       |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
openblocks-backend-1       |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
openblocks-backend-1       |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
openblocks-backend-1       |    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
openblocks-backend-1       |    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
openblocks-backend-1       |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
openblocks-backend-1       |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
openblocks-backend-1       |    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)openblocks-backend-1       | 2023-03-15 09:54:25.664 ERROR org.pf4j.AbstractPluginManager#loadPlugins:242    [main]: Field 'id' cannot be empty 
openblocks-backend-1       | org.pf4j.PluginRuntimeException: Field 'id' cannot be empty
openblocks-backend-1       |    at org.pf4j.AbstractPluginManager.validatePluginDescriptor(AbstractPluginManager.java:918)
openblocks-backend-1       |    at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:840)
openblocks-backend-1       |    at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:139)
openblocks-backend-1       |    at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:240)
openblocks-backend-1       |    at org.pf4j.spring.SpringPluginManager.init(SpringPluginManager.java:61)
openblocks-backend-1       |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
openblocks-backend-1       |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
openblocks-backend-1       |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
openblocks-backend-1       |    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
openblocks-backend-1       |    at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
openblocks-backend-1       |    at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
openblocks-backend-1       |    at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
openblocks-backend-1       |    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
openblocks-backend-1       |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
openblocks-backend-1       |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
openblocks-backend-1       |    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
openblocks-backend-1       |    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
openblocks-backend-1       |    at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64)
openblocks-backend-1       |    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
openblocks-backend-1       |    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420)
openblocks-backend-1       |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
openblocks-backend-1       |    at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
openblocks-backend-1       |    at com.openblocks.api.ServerApplication.main(ServerApplication.java:51)
openblocks-backend-1       |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
openblocks-backend-1       |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
openblocks-backend-1       |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
openblocks-backend-1       |    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
openblocks-backend-1       |    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
openblocks-backend-1       |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
openblocks-backend-1       |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
openblocks-backend-1       |    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

How can I suppress it?

**Comment by neon-balcony** [comment] 2023-03-16 03:42
Thanks for the repost, it should caused by that we put irrelevant JARs in our plugins folder and they leads to classloading errors, however it is fail safe and won't effect current system running. We'll have it fixed in next release.

**Comment by YoJayz** [comment] 2023-03-23 14:18
Hi @rhuanbarreto This bug has been fixed in our latest Docker [images](https://hub.docker.com/u/openblocksdev). Thanks again for reporting this! BTW, the latest Openblocks [v1.1.8](https://github.com/openblocks-dev/openblocks/releases/tag/v1.1.8) has been released, please check it now!

**Closed as completed** 2023-03-27 09:55 UTC
Labels: bug
